spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:mysql://localhost:3306/constructxpert_resource_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
  main:
    allow-bean-definition-overriding: true
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

openapi:
  service:
    title: RESOURCE-SERVICE doc
    version: 1.0.0
    url: http://localhost:9191/RESOURCE-SERVICE
